classDiagram
    class OutputStream { <<abstract>> }
    OutputStream <|-- FileOutputStream
    OutputStream <|-- ByteArrayOutputStream
    OutputStream <|-- BufferedOutputStream
    OutputStream <|-- DataOutputStream
    OutputStream <|-- PrintStream
    PrintStream <|-- SystemOut
    PrintStream <|-- SystemErr
    class SystemOut["System.out"]
    class SystemErr["System.err"]

    note for FileOutputStream "запись в файл"
    note for ByteArrayOutputStream "запись в массив байт (в память)"
    note for PrintStream "форматированный вывод (printf, println)"
