classDiagram
    class InputStream { <<abstract>> }
    InputStream <|-- FileInputStream
    InputStream <|-- ByteArrayInputStream
    InputStream <|-- BufferedInputStream
    InputStream <|-- DataInputStream
    InputStream <|-- SystemIn
    class SystemIn["System.in"]

    note for FileInputStream "чтение из файла"
    note for ByteArrayInputStream "чтение из массива байт (из памяти)"
    note for BufferedInputStream "буферизированное чтение (ускоряет)"
    note for DataInputStream "чтение примитивных типов"
    note for SystemIn "стандартный ввод (клавиатура)"
